openapi: 3.2.1

info:
  title: API Key 
  version: 1.0.0
  description: Manage API clients and their API keys

server: 
  url: http://localhost:3000/api/v1

tags: 
  - name: Client
  - name: API Key

###
paths: 
  /clients:
    'post':
      tags:   
        - Client
      description: Register a new API client

      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - name
                - isActive
              properties: 
                name: 
                  type: string
                isActive: 
                  type: boolean
      responses: 
        '201':
          description: Client created successfully
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: Client created 
                  client: 
                    type: object
                    properties: 
                      id: 
                        type: string
                        format: uuid
                      name: 
                        type: string
                      isActive: 
                        type: boolean
        '409':
          description: Client already exist
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                    example: false
                  message: 
                    type: string
                    example: Client already exist
        '400':
          $ref: '#/components/responses/ValidationError'
        
        '500':
          $ref: '#/components/responses/ServerError'



####
components: 
  responses: 
    ValidationError:
      description: Validation failed
      content: 
        application/json:
          schema: 
            type: object
            properties: 
              success: 
                type: boolean
                example: false
              message:  
                type: string
                example: validation failed
              error: 
                type: array
                items: 
                  type: object
    ServerError:
      description: Internal server error
      content: 
        application/json:
          schema:
            type: object
            properties: 
              success:
                type: boolean
                example: false
              message: 
                type: string
                example: Internal server error
              


                        
                    

