openapi: 3.2.0

info:
  title: API Key 
  version: 1.0.0
  description: Manage API clients and their API keys

server: 
  url: http://localhost:3000/api/v1

tags: 
  - name: Client
  - name: API Key

###
paths: 
  /clients:
    'post':
      tags:   
        - Client
      description: Register a new API client

      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - name
                - isActive
              properties: 
                name: 
                  type: string
                isActive: 
                  type: boolean
      responses: 
        '201':
          description: Client created successfully
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: Client created 
                  client: 
                    type: object
                    properties: 
                      id: 
                        type: string
                        format: uuid
                      name: 
                        type: string
                      isActive: 
                        type: boolean
        '409':
          description: Client already exist
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                    example: false
                  message: 
                    type: string
                    example: Client already exist
        '400':
          $ref: '#/components/responses/ValidationError'
        
        '500':
          $ref: '#/components/responses/ServerError'

    'get':
      tags: 
        - Client
      description: Get list of API clients data
    
      responses: 
        '200':
          description: Clients list retrieved
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: Clients list retrieved
                  clients: 
                    type: array
                    items: 
                      type: object
                      properties: 
                        id: 
                          type: string
                          format: uuid
                        name: 
                          type: string
                        isActive:
                          type: boolean
                        createdAt: 
                          type: string
                          format: date-time

        '500':
          $ref: '#/components/responses/ServerError'               

  /clients/{clientId}:
    'get':
      tags:
        - Client
      description: Retrieve the client data

      parameters: 
        - $ref: '#/components/parameters/ClientId'
      
      responses: 
        '200':
          description: The client data retrieved
          content: 
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: The client data retrieved
                  client:
                    type: object
                    properties: 
                      id: 
                        type: string
                        format: uuid
                      name: 
                        type: string
                      isActive: 
                        type: boolean
                      createdAt: 
                        type: string
                        format: date-time


        '404':
          $ref: '#/components/responses/NotFound'
        
        '500':
          $ref: '#/components/responses/ServerError'

    'patch':
      tags:   
        - Client
      description: Update API client data

      parameters:
        - $ref: '#/components/parameters/ClientId'

      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                name: 
                  type: string
                isActive: 
                  type: boolean
      
      responses: 
        '200':  
          description: API client data updated
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: API client data updated
                  client: 
                    type: object
                    properties: 
                      name: 
                        type: string
                      isActive: 
                        type: boolean
        
        '404':
          $ref: '#/components/responses/NotFound'
        
        '400':
          $ref: '#/components/responses/ValidationError'
        
        '500':
          $ref: '#components/responses/ServerError'

    'delete':
      tags: 
        - Client
      description: Delete the API client

      parameters:
        - $ref: '#/components/parameters/ClientId'
      
      responses: 
        '200':
          description: API client deleted
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: Client deleted

        '404':
          $ref: '#/components/responses/NotFound'
        
        '500':
          $ref: '#/components/responses/ServerError'

####
components: 
  responses: 
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Validation failed
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: name
                    message:
                      type: string
                      example: Name is required

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Internal server error

    NotFound:
      description: Resource not found  
      content: 
        application/json:
          schema: 
            type: object
            properties: 
              success: 
                type: boolean
                example: false
              message: 
                type: string
                example: Resource not found 

  parameters: 
    ClientId:
      name: clientId
      in: path
      required: true
      description: The unique identifier for the client
      schema: 
        type: string
        format: uuid
      



                        
                    

